# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='shakara_category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Fashion', 'Fashion'), ('Wellness', 'Wellness'), ('Lifestyle', 'Lifestyle'), ('Spa', 'Spa')], default='Beauty', max_length=100),
        ),
    ]
