# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_shakara_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-timestamp', '-updated', '-title']},
        ),
        migrations.AddField(
            model_name='service',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 9, 15, 44, 50, 945618, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
