# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180409_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='shakara_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='services.Category'),
        ),
    ]
