# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180409_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, to='services.Category'),
        ),
    ]
