# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slugy',
            field=models.SlugField(blank=True),
        ),
    ]
