# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import shops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=200, null=True)),
                ('shop_description', models.TextField(blank=True, null=True)),
                ('dashboard_banner_image_1', models.ImageField(blank=True, null=True, upload_to=shops.models.upload_location)),
                ('user_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=shops.models.upload_location)),
                ('work_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=shops.models.upload_location)),
                ('category', models.CharField(choices=[('Beauty', 'Beauty'), ('Fashion', 'Fashion'), ('Wellness', 'Wellness'), ('Lifestyle', 'Lifestyle')], max_length=100)),
                ('let_client_book_online', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('map_embed', models.CharField(blank=True, max_length=200, null=True)),
                ('cancellation_policy', models.TextField()),
                ('mobile_number', models.CharField(max_length=11)),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='manager_workers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
