# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
