# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20180222_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopaccount',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopaccount',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Fashion', 'Fashion'), ('Wellness', 'Wellness'), ('Lifestyle', 'Lifestyle'), ('Spa', 'Spa')], max_length=100),
        ),
    ]
