# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20180222_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='business_bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='business_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='shop_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
