# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopaccount_shop_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopaccount',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
