# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 11:48
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20180222_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='work_image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=shops.models.upload_location),
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='work_image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=shops.models.upload_location),
        ),
    ]
