# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 12:10
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20180115_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='user_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=shops.models.upload_location),
        ),
    ]
