# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shopaccount_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopaccount',
            old_name='profession',
            new_name='service',
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='business_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
