# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_serviceoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
