# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20180131_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
