# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20180323_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='working_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
