# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shopaccount_featured'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profession',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='profession',
            new_name='service',
        ),
    ]
