# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20180201_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=500.0, max_digits=100, null=True),
        ),
    ]
