# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopaccount',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Fashion', 'Fashion'), ('Wellness', 'Wellness'), ('Spa', 'Spa'), ('Lifestyle', 'Lifestyle')], max_length=100),
        ),
    ]
