# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20180213_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='shop_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
