# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_shopaccount_shop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopaccount',
            name='let_client_book_online',
            field=models.BooleanField(default=True),
        ),
    ]
