# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_auto_20180214_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='business_bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='business_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
