# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 01:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('booking_date', models.DateTimeField()),
                ('optional_mobile_contact', models.CharField(blank=True, max_length=11, null=True)),
                ('optional_names', models.CharField(blank=True, max_length=100, null=True)),
                ('promotional_code', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_notes', models.TextField()),
                ('booking_code', models.CharField(max_length=5)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.ShopAccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
