# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='optional_mobile_contact',
            new_name='mobile_contact',
        ),
        migrations.AlterField(
            model_name='booking',
            name='extra_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
