# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20180113_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
