# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20180113_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_id', to='shops.ShopAccount'),
        ),
    ]
