# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20180223_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
