# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20180223_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
