# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20180201_0248'),
        ('bookings', '0005_auto_20180114_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='select_services', to='shops.Service'),
        ),
    ]
