# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=5, default=0.05, max_digits=10),
        ),
    ]
