# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20180201_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mode_of_payment',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash')], default=datetime.datetime(2018, 2, 2, 12, 1, 18, 606274, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
