# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='+2347010550325', max_length=15, null=True),
        ),
    ]
