# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_useraddress_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='discounts',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
