# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180226_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='example: +2347010550325', max_length=15, null=True),
        ),
    ]
