# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_curatedproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='shop',
        ),
    ]
