# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
