# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
